app:
  name: "web_app"
  version: "1.0.1"
  port: 8081
  model: "dev"

mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "root"
  database: "mydb"
  max_open_conns: 50
  max_idle_conns: 10

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: "0"

log:
  level: "Debug"
  filename: "log_all.log"
  max_size: 100
  max_backups: 3
  max_age: 24

